from setuptools import setup, find_packages

setup(
    name="dacapo-ml",
    description="Framework for easy composition of volumetric machine learning jobs.",
    long_description=open("README.md", "r").read(),
    long_description_content_type="text/markdown",
    version="0.1",
    url="https://github.com/funkelab/dacapo",
    author="Jan Funke, Will Patton",
    author_email="funkej@janelia.hhmi.org, pattonw@janelia.hhmi.org",
    license="MIT",
    packages=find_packages(),
    entry_points={"console_scripts": ["dacapo=scripts.dacapo:cli"]},
    include_package_data=True,
    install_requires=[
        "numpy",
        "pyyaml",
        "zarr",
        "cattrs",
        "pymongo",
        "tqdm",
        "simpleitk",
        "lazy-property",
        "neuroglancer",
        "torch",
        "fibsem_tools",
        "attrs",
        "bokeh",
        "daisy>=1.0",
        "funlib.math>=0.1",
        "funlib.geometry>=0.2",
        "funlib.persistence @ git+https://github.com/funkelab/funlib.persistence",
        "funlib.evaluate @ git+https://github.com/pattonw/funlib.evaluate",
        "cremi @ git+https://github.com/cremi/cremi_python@python3",
        "gunpowder @ git+https://github.com/funkey/gunpowder@v1.3-dev",
        "lsd @ git+https://github.com/pattonw/lsd@no-convenience-imports",
    ],
)
